project:
  type: website 
  resources:
    - filter.js
    - documents/*/*
    - documents/talleres-cursos/multinivel_taller/*
    - documents/talleres-cursos/multinivel_taller/libs/*/*
    - documents/talleres-cursos/multinivel_taller/taller-multinivel-files/*/*
    - documents/talleres-cursos/tallerATOM/*/*/*/*
    - documents/doctorado-psicologia/*/*/*/*/*
    - documents/talleres-cursos/escritura-academica/libs/*
  render:
    - "*.qmd"
  output-dir: "docs"

website:
  title: "jc-castillo"
  page-footer:
    background: "#000000"
    left: |
      [2025]()
    center:
      - href: https://github.com/juancarloscastillo/jc-quarto
        icon: github
        aria-label: GitHub
    right: |
       Last Update: {{< modified isodate>}} 
  navbar:
    tools:
      # Quitamos el icono de Google Translate y dejamos GitHub:
      - icon: github
        href: https://github.com/juancarloscastillo
      - text: "🌐 Idioma"
        href: "#"
        id: google_translate_placeholder      
    left:
      - href: index.qmd#proyectosh1
        text: Proyectos
      - href: index.qmd#publicationh1
        text: Publicaciones
      - href: index.qmd#docenciah1
        text: Docencia
      - href: index.qmd#tesish1
        text: Tesis  
      - href: index.qmd#blogh1
        text: Blog
      - href: index.qmd#galeriah1
        text: Galería
      - links.qmd
      - contacto.qmd
  page-navigation: true

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: 
      - styles.css
    toc: true
    linkcolor: "#e1cc97"
    extensions:
      - banner-override
    include-in-header: translate.html

freeze: auto
