project:
  type: website

website:
  title: "jc-castillo"
  navbar:
    # pinned: true
    left:
      - href: index.qmd#publicationh1
        text: Publicaciones y Presentaciones
      - href: index.qmd#docenciah1
        text: Docencia
      - href: index.qmd#proyectosh1
        text: Proyectos
      - href: index.qmd#blogh1
        text: Blog
      - links.qmd
      - contacto.qmd
      
format:
  html:
#    theme: cosmo
    theme: 
     dark: darkly
     light: flatly
    css: styles.css
    toc: true



