project:
  type: website
  render: 
        - "*.qmd"

website:
  title: "jc-castillo"
  navbar:
    # pinned: true
    left:
      - href: index.qmd#publicationh1
        text: Publicaciones y Presentaciones
      - href: index.qmd#docenciah1
        text: Docencia
      - href: index.qmd#proyectosh1
        text: Proyectos
      - href: index.qmd#blogh1
        text: Blog
      - href: index.qmd#tesish1
        text: Tesis
      - links.qmd
      - contacto.qmd
      
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: 
      - styles.css
    toc: true
    linkcolor: "#6C8EBF"
    grid:
      sidebar-width: 0px
      body-width: 1728px
      margin-width: 192px




