project:
  type: website

website:
  title: "jc-castillo"
  navbar:
    pinned: true
    left:
      - href: index.qmd#listing-docencia
        text: Docencia
      - href: index.qmd#listing-proyectos
        text: Proyectos
      - href: index.qmd#listing-blog
        text: Post Recientes
      - links.qmd
      - contacto.qmd
      
format:
  html:
#    theme: cosmo
    theme: 
     dark: darkly
     light: flatly
    css: styles.css
    toc: true



