project:
  type: website 
  resources:
          - filter.js
          - documents/*/*
          - documents/talleres-cursos/multinivel_taller/*
          - documents/talleres-cursos/multinivel_taller/libs/*/*
          - documents/talleres-cursos/multinivel_taller/taller-multinivel-files/*/*
          - documents/talleres-cursos/tallerATOM/*/*/*/*
          - documents/doctorado-psicologia/*/*/*/*/*
          - documents/talleres-cursos/escritura-academica/libs/*
  render:
        - "*.qmd"
  output-dir: "docs"
website:
  title: "jc-castillo"
  page-footer:
    background: "#000000"
    left: |
      [2025]()
    center:
      - href: https://github.com/juancarloscastillo/jc-quarto
        icon: github
        aria-label: GitHub
    right: |
       Last Update: {{< modified isodate>}} 
  navbar:
    tools:
       - icon: translate
         href: https://1-jc--castillo-com.translate.goog/?_x_tr_sl=es&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp&_x_tr_enc=1    # pinned: true
       - icon: github
         href: https://github.com/juancarloscastillo
    left:
      - href: index.qmd#proyectosh1
        text: Proyectos
      - href: index.qmd#publicationh1
        text: Publicaciones
      - href: index.qmd#docenciah1
        text: Docencia
      - href: index.qmd#tesish1
        text: Tesis  
      - href: index.qmd#blogh1
        text: Blog
      - href: index.qmd#galeriah1
        text: Galería
      - links.qmd
      - contacto.qmd
  page-navigation: true
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: 
      - styles.css
    toc: true
    linkcolor: "#e1cc97"
    extensions:
      - banner-override
freeze: auto



