---
title : "The Crowdsourced Replication Initiative: Investigating Immigration and Social Policy Preferences. Executive Report"
date : "2019-01-01"
author : "Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Adem, Muna; Adriaans, Jule; Alvarez-Benjumea, Amalia; Andersen, Henrik Kenneth; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Balzer, Dave; Bauer, Gerrit; Bauer, Paul; Baumann, Markus; Baute, Sharon; Benoit, Verena; Berning, Carl; Bernauer, Julian; Berthold, Anna; Bethke, Felix; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes; Bol, Thijs; Bobzien, Licia; Bohman, Andrea; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin; Castillo, Juan Carlos; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; Edelmann, Achim; Ecker, Alejandro; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Gavras, Konstantin; Gayle, Vernon; Gaasendam, Chris; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Greinert, Alexander; Gross, Martin; Gromping, Max; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hoffler, Jan H.; Hovermann, Andreas; Huth, Nora; Hunger, Sophia; Hunkler, Christian; Ignacz, Zsofia; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kauff, Mathias; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Kurti, Dafina; Lersch, Philipp M.; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar Jose; McManus, Patricia; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Katja; Schmidt, Regine; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Schupp, Jurgen; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils; Sternberg, Sebastian; Stiers, Dieter; Striessnig, Erich; Stojmenovska, Dragana; Storz, Nora; Stroppe, Anne-Kathrin; Teltemann, Janna; Tibajev, Andrey; Tung, Brian B.; Vagni, Giacomo; Van Assche, Jasper; van der Linden, Meta; van der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Wagemans, Fieke M. A.; Wagner, Kyle; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Yamada, Yuki; Zakula, Bjorn; Ziller, Conrad; Zins, Stefan; Zhang, Nan; Zoltak, Tomasz & Nguyen, Hung H. V."
categories : ["Report"]
publication : " OSF Preprint  SocArXiv [https://doi.org/10.31235/osf.io/6j9qb](https://doi.org/10.31235/osf.io/6j9qb)"
publication_short : " OSF Preprint  SocArXiv [https://doi.org/10.31235/osf.io/6j9qb](https://doi.org/10.31235/osf.io/6j9qb)"
abstract : "In an era of mass migration, social scientists, populist parties and social movements raise concerns over the future of immigration-destination societies. What impacts does this have on policy and social solidarity? Comparative cross-national research, relying mostly on secondary data, has findings in different directions. There is a threat of selective model reporting and lack of replicability. The heterogeneity of countries obscures attempts to clearly define data-generating models. P-hacking and HARKing lurk among standard research practices in this area. This project employs crowdsourcing to address these issues. It draws on replication, deliberation, meta-analysis and harnessing the power of many minds at once. The Crowdsourced Replication Initiative carries two main goals, (a) to better investigate the linkage between immigration and social policy preferences across countries, and (b) to develop crowdsourcing as a social science method. The Executive Report provides short reviews of the area of social policy preferences and immigration, and the methods and impetus behind crowdsourcing plus a description of the entire project. Three main areas of findings will appear in three papers, that are registered as PAPs or in process."
abstract_short : ""
about:
  template: marquee
---
---


::: {.callout-note title="How to cite this work"}

Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Adem, Muna; Adriaans, Jule; Alvarez-Benjumea, Amalia; Andersen, Henrik Kenneth; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Balzer, Dave; Bauer, Gerrit; Bauer, Paul; Baumann, Markus; Baute, Sharon; Benoit, Verena; Berning, Carl; Bernauer, Julian; Berthold, Anna; Bethke, Felix; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes; Bol, Thijs; Bobzien, Licia; Bohman, Andrea; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin; Castillo, Juan Carlos; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; Edelmann, Achim; Ecker, Alejandro; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Gavras, Konstantin; Gayle, Vernon; Gaasendam, Chris; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Greinert, Alexander; Gross, Martin; Gromping, Max; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hoffler, Jan H.; Hovermann, Andreas; Huth, Nora; Hunger, Sophia; Hunkler, Christian; Ignacz, Zsofia; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kauff, Mathias; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Kurti, Dafina; Lersch, Philipp M.; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar Jose; McManus, Patricia; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Katja; Schmidt, Regine; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Schupp, Jurgen; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils; Sternberg, Sebastian; Stiers, Dieter; Striessnig, Erich; Stojmenovska, Dragana; Storz, Nora; Stroppe, Anne-Kathrin; Teltemann, Janna; Tibajev, Andrey; Tung, Brian B.; Vagni, Giacomo; Van Assche, Jasper; van der Linden, Meta; van der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Wagemans, Fieke M. A.; Wagner, Kyle; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Yamada, Yuki; Zakula, Bjorn; Ziller, Conrad; Zins, Stefan; Zhang, Nan; Zoltak, Tomasz & Nguyen, Hung H. V. (2019). *The Crowdsourced Replication Initiative: Investigating Immigration and Social Policy Preferences. Executive Report*.  OSF Preprint  SocArXiv [https://doi.org/10.31235/osf.io/6j9qb](https://doi.org/10.31235/osf.io/6j9qb)

:::

