---
title : "Observing Many Researchers Using the Same Data and Hypothesis Reveals a Hidden Universe of Uncertainty"
date : "2022-11-01"
author : "Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Nguyen, Hung H. V.; Adem, Muna; Adriaans, Jule; Alvarez-Benjumea, Amalia; Andersen, Henrik K.; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Balzer, Dave; Bauer, Gerrit; Bauer, Paul C.; Baumann, Markus; Baute, Sharon; Benoit, Verena; Bernauer, Julian; Berning, Carl; Berthold, Anna; Bethke, Felix S.; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes N.; Bobzien, Licia; Bohman, Andrea; Bol, Thijs; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin B.; Carlos-Castillo, Juan; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; Ecker, Alejandro; Edelmann, Achim; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Gaasendam, Chris; Gavras, Konstantin; Gayle, Vernon; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Gromping, Max; Gross, Martin; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hovermann, Andreas; Hunger, Sophia; Hunkler, Christian; Huth, Nora; Ignacz, Zsofia S.; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kauff, Mathias; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Sinatra, Dafina Kurti; Langenkamp, Alexander; Lersch, Philipp M.; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan E.; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar J.; McManus, Patricia; McWagner, Kyle; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna O.; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel R.; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Regine; Schmidt, Katja M.; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Schupp, Jurgen; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils; Sternberg, Sebastian; Stiers, Dieter; Stojmenovska, Dragana; Storz, Nora; Striessnig, Erich; Stroppe, Anne-Kathrin; Teltemann, Janna; Tibajev, Andrey; Tung, Brian; Vagni, Giacomo; Van Assche, Jasper; van der Linden, Meta; van der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Voicu, Bogdan; Wagemans, Fieke; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Yamada, Yuki; Zhang, Nan; Ziller, Conrad; Zins, Stefan & Zoltak, Tomasz"
categories : ["Journal Article"]
publication : "Proceedings of the National Academy of Sciences, 119(44) e2203150119  [https://doi.org/10.1073/pnas.2203150119](https://doi.org/10.1073/pnas.2203150119)"
publication_short : "Proceedings of the National Academy of Sciences, 119(44) e2203150119  [https://doi.org/10.1073/pnas.2203150119](https://doi.org/10.1073/pnas.2203150119)"
abstract : "This study explores how researchers’ analytical choices affect the reliability of scientific findings. Most discussions of reliability problems in science focus on systematic biases. We broaden the lens to emphasize the idiosyncrasy of conscious and unconscious decisions that researchers make during data analysis. We coordinated 161 researchers in 73 research teams and observed their research decisions as they used the same data to independently test the same prominent social science hypothesis: that greater immigration reduces support for social policies among the public. In this typical case of social science research, research teams reported both widely diverging numerical findings and substantive conclusions despite identical start conditions. Researchers’ expertise, prior beliefs, and expectations barely predict the wide variation in research outcomes. More than 95% of the total variance in numerical results remains unexplained even after qualitative coding of all identifiable decisions in each team’s workflow. This reveals a universe of uncertainty that remains hidden when considering a single study in isolation. The idiosyncratic nature of how researchers’ results and conclusions varied is a previously underappreciated explanation for why many scientific hypotheses remain contested. These results call for greater epistemic humility and clarity in reporting scientific findings."
abstract_short : ""
about:
  template: marquee
---
---


::: {.callout-note title="How to cite this work"}

Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Nguyen, Hung H. V.; Adem, Muna; Adriaans, Jule; Alvarez-Benjumea, Amalia; Andersen, Henrik K.; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Balzer, Dave; Bauer, Gerrit; Bauer, Paul C.; Baumann, Markus; Baute, Sharon; Benoit, Verena; Bernauer, Julian; Berning, Carl; Berthold, Anna; Bethke, Felix S.; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes N.; Bobzien, Licia; Bohman, Andrea; Bol, Thijs; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin B.; Carlos-Castillo, Juan; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; Ecker, Alejandro; Edelmann, Achim; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Gaasendam, Chris; Gavras, Konstantin; Gayle, Vernon; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Gromping, Max; Gross, Martin; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hovermann, Andreas; Hunger, Sophia; Hunkler, Christian; Huth, Nora; Ignacz, Zsofia S.; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kauff, Mathias; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Sinatra, Dafina Kurti; Langenkamp, Alexander; Lersch, Philipp M.; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan E.; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar J.; McManus, Patricia; McWagner, Kyle; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna O.; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel R.; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Regine; Schmidt, Katja M.; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Schupp, Jurgen; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils; Sternberg, Sebastian; Stiers, Dieter; Stojmenovska, Dragana; Storz, Nora; Striessnig, Erich; Stroppe, Anne-Kathrin; Teltemann, Janna; Tibajev, Andrey; Tung, Brian; Vagni, Giacomo; Van Assche, Jasper; van der Linden, Meta; van der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Voicu, Bogdan; Wagemans, Fieke; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Yamada, Yuki; Zhang, Nan; Ziller, Conrad; Zins, Stefan & Zoltak, Tomasz (2022). *Observing Many Researchers Using the Same Data and Hypothesis Reveals a Hidden Universe of Uncertainty*. Proceedings of the National Academy of Sciences, 119(44) e2203150119  [https://doi.org/10.1073/pnas.2203150119](https://doi.org/10.1073/pnas.2203150119)

:::

