---
title : "The Reliability of Replications: A Study in Computational Reproductions"
date : "2025-03-01"
author : "Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Adem, Muna; Adriaans, Jule; Akdeniz, Esra; Alvarez-Benjumea, Amalia; Andersen, Henrik K.; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Bai, Ling; Balzer, Dave; Bauer, Paul C.; Bauer, Gerrit; Baumann, Markus; Baute, Sharon; Benoit, Verena; Bernauer, Julian; Berning, Carl; Berthold, Anna; Bethke, Felix S.; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes N.; Bobzien, Licia; Bohman, Andrea; Bol, Thijs; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin; Castillo, Juan-Carlos; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; De Rooij, Eline A.; Ecker, Alejandro; Edelmann, Achim; Eder, Christina; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Freire, Danilo; Gaasendam, Chris; Gavras, Konstantin; Gayle, Vernon; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Gromping, Max; Gross, Martin; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Halbherr, Verena; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hoffler, Jan H.; Hovermann, Andreas; Hunger, Sophia; Hunkler, Christian; Huth-Stockle, Nora; Ignacz, Zsofia S.; Israel, Sabine; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kanjana, Jennifer; Kauff, Mathias; Khan, Salman; Khatua, Sayak; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Sinatra, Dafina Kurti; Langenkamp, Alexander; Lee, Robin C.; Lersch, Philipp M.; Liu, David; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan E.; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar J.; McDonnell, Robert; McManus, Patricia; McWagner, Kyle; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna; Pickup, Mark; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel; Reichert, Frank; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Petrarca, Constanza Sanhueza; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Katja; Schmidt, Regine; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils D.; Sternberg, Sebastian; Stiers, Dieter; Stojmenovska, Dragana; Storz, Nora; Striessnig, Erich; Stroppe, Anne-Kathrin; Suchow, Jordan W.; Teltemann, Janna; Tibajev, Andrey; Tung, Brian; Vagni, Giacomo; Van Assche, Jasper; Van Der Linden, Meta; Van Der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Voicu, Bogdan; Wagemans, Fieke; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Wu, Cary; Yamada, Yuki; Zakula, Bjorn; Zhang, Nan; Ziller, Conrad; Zins, Stefan; Zoltak, Tomasz & Nguyen, Hung H.V."
categories : ["Journal Article"]
publication : "Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)"
publication_short : "Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)"
abstract : "This study investigates researcher variability in computational reproduction, an activity for which it is least expected. Eighty-five independent teams attempted numerical replication of results from an original study of policy preferences and immigration. Reproduction teams were randomly grouped into a ‘transparent group’ receiving original study and code or ‘opaque group’ receiving only a method and results description and no code. The transparent group mostly verified original results (95.7% same sign and               p               -value cutoff), while the opaque group had less success (89.3%). Second-decimal place exact numerical reproductions were less common (76.9 and 48.1%). Qualitative investigation of the workflows revealed many causes of error, including mistakes and procedural variations. When curating mistakes, we still find that only the transparent group was reliably successful. Our findings imply a need for transparency, but also more. Institutional checks and less subjective difficulty for researchers ‘doing reproduction’ would help, implying a need for better training. We also urge increased awareness of complexity in the research process and in ‘push button’ replications."
abstract_short : ""
about:
  template: marquee
  links:
    - icon: NA
      href: NA
---


::: {.callout-note title="How to cite this work"}

Breznau, Nate; Rinke, Eike Mark; Wuttke, Alexander; Adem, Muna; Adriaans, Jule; Akdeniz, Esra; Alvarez-Benjumea, Amalia; Andersen, Henrik K.; Auer, Daniel; Azevedo, Flavio; Bahnsen, Oke; Bai, Ling; Balzer, Dave; Bauer, Paul C.; Bauer, Gerrit; Baumann, Markus; Baute, Sharon; Benoit, Verena; Bernauer, Julian; Berning, Carl; Berthold, Anna; Bethke, Felix S.; Biegert, Thomas; Blinzler, Katharina; Blumenberg, Johannes N.; Bobzien, Licia; Bohman, Andrea; Bol, Thijs; Bostic, Amie; Brzozowska, Zuzanna; Burgdorf, Katharina; Burger, Kaspar; Busch, Kathrin; Castillo, Juan-Carlos; Chan, Nathan; Christmann, Pablo; Connelly, Roxanne; Czymara, Christian S.; Damian, Elena; De Rooij, Eline A.; Ecker, Alejandro; Edelmann, Achim; Eder, Christina; Eger, Maureen A.; Ellerbrock, Simon; Forke, Anna; Forster, Andrea; Freire, Danilo; Gaasendam, Chris; Gavras, Konstantin; Gayle, Vernon; Gessler, Theresa; Gnambs, Timo; Godefroidt, Amelie; Gromping, Max; Gross, Martin; Gruber, Stefan; Gummer, Tobias; Hadjar, Andreas; Halbherr, Verena; Heisig, Jan Paul; Hellmeier, Sebastian; Heyne, Stefanie; Hirsch, Magdalena; Hjerm, Mikael; Hochman, Oshrat; Hoffler, Jan H.; Hovermann, Andreas; Hunger, Sophia; Hunkler, Christian; Huth-Stockle, Nora; Ignacz, Zsofia S.; Israel, Sabine; Jacobs, Laura; Jacobsen, Jannes; Jaeger, Bastian; Jungkunz, Sebastian; Jungmann, Nils; Kanjana, Jennifer; Kauff, Mathias; Khan, Salman; Khatua, Sayak; Kleinert, Manuel; Klinger, Julia; Kolb, Jan-Philipp; Kolczynska, Marta; Kuk, John; Kunissen, Katharina; Sinatra, Dafina Kurti; Langenkamp, Alexander; Lee, Robin C.; Lersch, Philipp M.; Liu, David; Lobel, Lea-Maria; Lutscher, Philipp; Mader, Matthias; Madia, Joan E.; Malancu, Natalia; Maldonado, Luis; Marahrens, Helge; Martin, Nicole; Martinez, Paul; Mayerl, Jochen; Mayorga, Oscar J.; McDonnell, Robert; McManus, Patricia; McWagner, Kyle; Meeusen, Cecil; Meierrieks, Daniel; Mellon, Jonathan; Merhout, Friedolin; Merk, Samuel; Meyer, Daniel; Micheli, Leticia; Mijs, Jonathan; Moya, Cristobal; Neunhoeffer, Marcel; Nust, Daniel; Nygard, Olav; Ochsenfeld, Fabian; Otte, Gunnar; Pechenkina, Anna; Pickup, Mark; Prosser, Christopher; Raes, Louis; Ralston, Kevin; Ramos, Miguel; Reichert, Frank; Roets, Arne; Rogers, Jonathan; Ropers, Guido; Samuel, Robin; Sand, Gregor; Petrarca, Constanza Sanhueza; Schachter, Ariela; Schaeffer, Merlin; Schieferdecker, David; Schlueter, Elmar; Schmidt, Katja; Schmidt, Regine; Schmidt-Catran, Alexander; Schmiedeberg, Claudia; Schneider, Jurgen; Schoonvelde, Martijn; Schulte-Cloos, Julia; Schumann, Sandy; Schunck, Reinhard; Seuring, Julian; Silber, Henning; Sleegers, Willem; Sonntag, Nico; Staudt, Alexander; Steiber, Nadia; Steiner, Nils D.; Sternberg, Sebastian; Stiers, Dieter; Stojmenovska, Dragana; Storz, Nora; Striessnig, Erich; Stroppe, Anne-Kathrin; Suchow, Jordan W.; Teltemann, Janna; Tibajev, Andrey; Tung, Brian; Vagni, Giacomo; Van Assche, Jasper; Van Der Linden, Meta; Van Der Noll, Jolanda; Van Hootegem, Arno; Vogtenhuber, Stefan; Voicu, Bogdan; Wagemans, Fieke; Wehl, Nadja; Werner, Hannah; Wiernik, Brenton M.; Winter, Fabian; Wolf, Christof; Wu, Cary; Yamada, Yuki; Zakula, Bjorn; Zhang, Nan; Ziller, Conrad; Zins, Stefan; Zoltak, Tomasz & Nguyen, Hung H.V. (2025). *The Reliability of Replications: A Study in Computational Reproductions*. Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)

:::

