---
title : "The Reliability of Replications: A Study in Computational Reproductions"
date : "2025-03-01"
author : ["Nate Breznau", "Eike Mark Rinke", "Alexander Wuttke", "Muna Adem", "Jule Adriaans", "Esra Akdeniz", "Amalia Alvarez-Benjumea", "Henrik K. Andersen", "Daniel Auer", "Flavio Azevedo", "Oke Bahnsen", "Ling Bai", "Dave Balzer", "Paul C. Bauer", "Gerrit Bauer", "Markus Baumann", "Sharon Baute", "Verena Benoit", "Julian Bernauer", "Carl Berning", "Anna Berthold", "Felix S. Bethke", "Thomas Biegert", "Katharina Blinzler", "Johannes N. Blumenberg", "Licia Bobzien", "Andrea Bohman", "Thijs Bol", "Amie Bostic", "Zuzanna Brzozowska", "Katharina Burgdorf", "Kaspar Burger", "Kathrin Busch", "Juan-Carlos Castillo", "Nathan Chan", "Pablo Christmann", "Roxanne Connelly", "Christian S. Czymara", "Elena Damian", "Eline A. {De Rooij}", "Alejandro Ecker", "Achim Edelmann", "Christina Eder", "Maureen A. Eger", "Simon Ellerbrock", "Anna Forke", "Andrea Forster", "Danilo Freire", "Chris Gaasendam", "Konstantin Gavras", "Vernon Gayle", "Theresa Gessler", "Timo Gnambs", "Amelie Godefroidt", "Max Gromping", "Martin Gross", "Stefan Gruber", "Tobias Gummer", "Andreas Hadjar", "Verena Halbherr", "Jan Paul Heisig", "Sebastian Hellmeier", "Stefanie Heyne", "Magdalena Hirsch", "Mikael Hjerm", "Oshrat Hochman", "Jan H. Hoffler", "Andreas Hovermann", "Sophia Hunger", "Christian Hunkler", "Nora Huth-Stockle", "Zsofia S. Ignacz", "Sabine Israel", "Laura Jacobs", "Jannes Jacobsen", "Bastian Jaeger", "Sebastian Jungkunz", "Nils Jungmann", "Jennifer Kanjana", "Mathias Kauff", "Salman Khan", "Sayak Khatua", "Manuel Kleinert", "Julia Klinger", "Jan-Philipp Kolb", "Marta Kolczynska", "John Kuk", "Katharina Kunissen", "Dafina {Kurti Sinatra}", "Alexander Langenkamp", "Robin C. Lee", "Philipp M. Lersch", "David Liu", "Lea-Maria Lobel", "Philipp Lutscher", "Matthias Mader", "Joan E. Madia", "Natalia Malancu", "Luis Maldonado", "Helge Marahrens", "Nicole Martin", "Paul Martinez", "Jochen Mayerl", "Oscar J. Mayorga", "Robert McDonnell", "Patricia McManus", "Kyle McWagner", "Cecil Meeusen", "Daniel Meierrieks", "Jonathan Mellon", "Friedolin Merhout", "Samuel Merk", "Daniel Meyer", "Leticia Micheli", "Jonathan Mijs", "Cristobal Moya", "Marcel Neunhoeffer", "Daniel Nust", "Olav Nygard", "Fabian Ochsenfeld", "Gunnar Otte", "Anna Pechenkina", "Mark Pickup", "Christopher Prosser", "Louis Raes", "Kevin Ralston", "Miguel Ramos", "Frank Reichert", "Arne Roets", "Jonathan Rogers", "Guido Ropers", "Robin Samuel", "Gregor Sand", "Constanza {Sanhueza Petrarca}", "Ariela Schachter", "Merlin Schaeffer", "David Schieferdecker", "Elmar Schlueter", "Katja Schmidt", "Regine Schmidt", "Alexander Schmidt-Catran", "Claudia Schmiedeberg", "Jurgen Schneider", "Martijn Schoonvelde", "Julia Schulte-Cloos", "Sandy Schumann", "Reinhard Schunck", "Julian Seuring", "Henning Silber", "Willem Sleegers", "Nico Sonntag", "Alexander Staudt", "Nadia Steiber", "Nils D. Steiner", "Sebastian Sternberg", "Dieter Stiers", "Dragana Stojmenovska", "Nora Storz", "Erich Striessnig", "Anne-Kathrin Stroppe", "Jordan W. Suchow", "Janna Teltemann", "Andrey Tibajev", "Brian Tung", "Giacomo Vagni", "Jasper {Van Assche}", "Meta {Van Der Linden}", "Jolanda {Van Der Noll}", "Arno {Van Hootegem}", "Stefan Vogtenhuber", "Bogdan Voicu", "Fieke Wagemans", "Nadja Wehl", "Hannah Werner", "Brenton M. Wiernik", "Fabian Winter", "Christof Wolf", "Cary Wu", "Yuki Yamada", "Bjorn Zakula", "Nan Zhang", "Conrad Ziller", "Stefan Zins", "Tomasz Zoltak", "Hung H.V. Nguyen"]
categories : ["Journal Article"]
publication : "Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)"
publication_short : "Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)"
abstract : "This study investigates researcher variability in computational reproduction, an activity for which it is least expected. Eighty-five independent teams attempted numerical replication of results from an original study of policy preferences and immigration. Reproduction teams were randomly grouped into a ‘transparent group’ receiving original study and code or ‘opaque group’ receiving only a method and results description and no code. The transparent group mostly verified original results (95.7% same sign and               p               -value cutoff), while the opaque group had less success (89.3%). Second-decimal place exact numerical reproductions were less common (76.9 and 48.1%). Qualitative investigation of the workflows revealed many causes of error, including mistakes and procedural variations. When curating mistakes, we still find that only the transparent group was reliably successful. Our findings imply a need for transparency, but also more. Institutional checks and less subjective difficulty for researchers ‘doing reproduction’ would help, implying a need for better training. We also urge increased awareness of complexity in the research process and in ‘push button’ replications."
abstract_short : ""
about:
  template: marquee
  links:
    - icon: NA
      href: NA
---


::: {.callout-note title="How to cite this work"}

Nate Breznau, Eike Mark Rinke, Alexander Wuttke, Muna Adem, Jule Adriaans, Esra Akdeniz, Amalia Alvarez-Benjumea, Henrik K. Andersen, Daniel Auer, Flavio Azevedo, Oke Bahnsen, Ling Bai, Dave Balzer, Paul C. Bauer, Gerrit Bauer, Markus Baumann, Sharon Baute, Verena Benoit, Julian Bernauer, Carl Berning, Anna Berthold, Felix S. Bethke, Thomas Biegert, Katharina Blinzler, Johannes N. Blumenberg, Licia Bobzien, Andrea Bohman, Thijs Bol, Amie Bostic, Zuzanna Brzozowska, Katharina Burgdorf, Kaspar Burger, Kathrin Busch, Juan-Carlos Castillo, Nathan Chan, Pablo Christmann, Roxanne Connelly, Christian S. Czymara, Elena Damian, Eline A. De Rooij, Alejandro Ecker, Achim Edelmann, Christina Eder, Maureen A. Eger, Simon Ellerbrock, Anna Forke, Andrea Forster, Danilo Freire, Chris Gaasendam, Konstantin Gavras, Vernon Gayle, Theresa Gessler, Timo Gnambs, Amelie Godefroidt, Max Gromping, Martin Gross, Stefan Gruber, Tobias Gummer, Andreas Hadjar, Verena Halbherr, Jan Paul Heisig, Sebastian Hellmeier, Stefanie Heyne, Magdalena Hirsch, Mikael Hjerm, Oshrat Hochman, Jan H. Hoffler, Andreas Hovermann, Sophia Hunger, Christian Hunkler, Nora Huth-Stockle, Zsofia S. Ignacz, Sabine Israel, Laura Jacobs, Jannes Jacobsen, Bastian Jaeger, Sebastian Jungkunz, Nils Jungmann, Jennifer Kanjana, Mathias Kauff, Salman Khan, Sayak Khatua, Manuel Kleinert, Julia Klinger, Jan-Philipp Kolb, Marta Kolczynska, John Kuk, Katharina Kunissen, Dafina Kurti Sinatra, Alexander Langenkamp, Robin C. Lee, Philipp M. Lersch, David Liu, Lea-Maria Lobel, Philipp Lutscher, Matthias Mader, Joan E. Madia, Natalia Malancu, Luis Maldonado, Helge Marahrens, Nicole Martin, Paul Martinez, Jochen Mayerl, Oscar J. Mayorga, Robert McDonnell, Patricia McManus, Kyle McWagner, Cecil Meeusen, Daniel Meierrieks, Jonathan Mellon, Friedolin Merhout, Samuel Merk, Daniel Meyer, Leticia Micheli, Jonathan Mijs, Cristobal Moya, Marcel Neunhoeffer, Daniel Nust, Olav Nygard, Fabian Ochsenfeld, Gunnar Otte, Anna Pechenkina, Mark Pickup, Christopher Prosser, Louis Raes, Kevin Ralston, Miguel Ramos, Frank Reichert, Arne Roets, Jonathan Rogers, Guido Ropers, Robin Samuel, Gregor Sand, Constanza Sanhueza Petrarca, Ariela Schachter, Merlin Schaeffer, David Schieferdecker, Elmar Schlueter, Katja Schmidt, Regine Schmidt, Alexander Schmidt-Catran, Claudia Schmiedeberg, Jurgen Schneider, Martijn Schoonvelde, Julia Schulte-Cloos, Sandy Schumann, Reinhard Schunck, Julian Seuring, Henning Silber, Willem Sleegers, Nico Sonntag, Alexander Staudt, Nadia Steiber, Nils D. Steiner, Sebastian Sternberg, Dieter Stiers, Dragana Stojmenovska, Nora Storz, Erich Striessnig, Anne-Kathrin Stroppe, Jordan W. Suchow, Janna Teltemann, Andrey Tibajev, Brian Tung, Giacomo Vagni, Jasper Van Assche, Meta Van Der Linden, Jolanda Van Der Noll, Arno Van Hootegem, Stefan Vogtenhuber, Bogdan Voicu, Fieke Wagemans, Nadja Wehl, Hannah Werner, Brenton M. Wiernik, Fabian Winter, Christof Wolf, Cary Wu, Yuki Yamada, Bjorn Zakula, Nan Zhang, Conrad Ziller, Stefan Zins, Tomasz Zoltak, Hung H.V. Nguyen (2025). *The Reliability of Replications: A Study in Computational Reproductions*. Royal Society Open Science, 12(3) 241038  [https://doi.org/10.1098/rsos.241038](https://doi.org/10.1098/rsos.241038)

:::

