---
title : "¿Qué Puede Hacer La Cultura de La Escuela Para Aumentar La Participación Política de Sus Estudiantes? Un Estudio Exploratorio Sobre El Rol Del Liderazgo Distribuido y El Compromiso Organizacional Docente En Escuelas Chilenas"
date : "2015-01-01"
author : ["Eduardo Santander"]
publication : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "Varios autores han reconocido la importancia estratégica de la educación cívica en el fortalecimiento de las democracias modernas y la centralidad de la institución escolar como órgano fundamental en el proceso de alfabetización cívica y política de las nuevas generaciones. Generalmente, el acento se ha puesto o en las características de un currículo democrático; o en el modelaje de didácticas de aula que favorecerían la formación de disposiciones pro-cívicas, pero poco se ha dicho sobre si la cultura de la escuela (esto es, sus prácticas y rutinas institucionales) tendría algún relación con el mejoramiento de las capacidades y destrezas cívicas de los estudiantes. Asimismo, nuevas conceptualizaciones de liderazgo escolar, como el liderazgo distribuido, han desafiado la visión gerencialista de la gestión escolar, lo que invita a evaluar su eficacia en la mejora de las habilidades cívicas de los estudiantes. El liderazgo distribuido supone el ejercicio de un estilo más descentralizado de gobierno institucional, en donde profesores destacados y otros miembros relevantes de la comunidad escolar asumen un rol más protagónico en la toma de decisiones sobre temas relativos a la dirección de la escuela. Asimismo, uno de los grandes retos que, en la actualidad, enfrentan las instituciones de educación escolar, es el de crear estrategias útiles para que los docentes se comprometan con los objetivos organizacionales y se integren activamente en los proyectos institucionales en el largo plazo. A partir de los datos informados por el Estudio Internacional de Educación Cívica y Formación Ciudadana (2009) para Chile, busca evaluar el rol del liderazgo distribuido de los directores y del compromiso organizacional docente de los profesores en la mejora de las habilidades cívicas de los estudiantes, considerando sus expresiones tanto manifiestas (medibles y observables) como latentes (potencialmente traducibles en formas manifiestas). Los resultados, obtenidos a partir de la estimación de modelos multinivel, exhiben que ni el compromiso organizacional docente ni el liderazgo distribuido se asocian con mayores expectativas de participación política, ni latente ni manifiesta. Si bien los parámetros son positivos, la relación no es estadísticamente significativa a niveles convencionales. Sin embargo, la participación política latente y manifiesta sí es significativa y positiva para las variables individuales de participación y valoración del involucramiento en la toma de decisiones de la escuela, lo que presta apoyo empírico a la hipótesis de que los estudiantes, más que aprender implícitamente sobre ciudadanía a partir de rutinas organizacionales de mayor horizontalidad, aprenden en el marco de un ejercicio cotidiano y sistemático de ciudadanía al interior de sus contextos socializantes. La socialización política, por ende, se constituye en un proceso de práctica individual de la democracia y no por asociación con figuras de autoridad. La investigación, asimismo, reafirma el núcleo conceptual presente en el relato sobre ciudadanía adscrito a las reformas curriculares sancionadas en la década del 2000 en Chile, en el sentido de un sello en la educación ciudadana como parte integral del proceso formativo de la escuela, que excede un aprendizaje meramente cognitivo y que se proyecta y actualiza en los espacios institucionales de deliberación y participación política. Finalmente, el autor entrega valiosa evidencia descriptiva sobre el comportamiento del liderazgo distribuido y del compromiso organizacional en las escuelas chilenas."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: documents/pdf/SantanderTesisVersionFinal.pdf
---
---

# Resumen
Varios autores han reconocido la importancia estratégica de la educación cívica en el
fortalecimiento de las democracias modernas y la centralidad de la institución escolar
como órgano fundamental en el proceso de alfabetización cívica y política de las nuevas
generaciones. Generalmente, el acento se ha puesto o en las características de un
currículo democrático; o en el modelaje de didácticas de aula que favorecerían la
formación de disposiciones pro-cívicas, pero poco se ha dicho sobre si la cultura de la
escuela (esto es, sus prácticas y rutinas institucionales) tendría algún relación con el
mejoramiento de las capacidades y destrezas cívicas de los estudiantes. Asimismo,
nuevas conceptualizaciones de liderazgo escolar, como el liderazgo distribuido, han
desafiado la visión gerencialista de la gestión escolar, lo que invita a evaluar su eficacia
en la mejora de las habilidades cívicas de los estudiantes. El liderazgo distribuido
supone el ejercicio de un estilo más descentralizado de gobierno institucional, en donde
profesores destacados y otros miembros relevantes de la comunidad escolar asumen un
rol más protagónico en la toma de decisiones sobre temas relativos a la dirección de la
escuela. Asimismo, uno de los grandes retos que, en la actualidad, enfrentan las
instituciones de educación escolar, es el de crear estrategias útiles para que los docentes
se comprometan con los objetivos organizacionales y se integren activamente en los
proyectos institucionales en el largo plazo. A partir de los datos informados por el
Estudio Internacional de Educación Cívica y Formación Ciudadana (2009) para Chile,
busca evaluar el rol del liderazgo distribuido de los directores y del compromiso
organizacional docente de los profesores en la mejora de las habilidades cívicas de los
estudiantes, considerando sus expresiones tanto manifiestas (medibles y observables)
como latentes (potencialmente traducibles en formas manifiestas).
Los resultados, obtenidos a partir de la estimación de modelos multinivel, exhiben que
ni el compromiso organizacional docente ni el liderazgo distribuido se asocian con
mayores expectativas de participación política, ni latente ni manifiesta. Si bien los
parámetros son positivos, la relación no es estadísticamente significativa a niveles
convencionales. Sin embargo, la participación política latente y manifiesta sí es
significativa y positiva para las variables individuales de participación y valoración del
involucramiento en la toma de decisiones de la escuela, lo que presta apoyo empírico a
la hipótesis de que los estudiantes, más que aprender implícitamente sobre ciudadanía
a partir de rutinas organizacionales de mayor horizontalidad, aprenden en el marco de
un ejercicio cotidiano y sistemático de ciudadanía al interior de sus contextos
socializantes. La socialización política, por ende, se constituye en un proceso de práctica
individual de la democracia y no por asociación con figuras de autoridad. La
investigación, asimismo, reafirma el núcleo conceptual presente en el relato sobre
ciudadanía adscrito a las reformas curriculares sancionadas en la década del 2000 en
Chile, en el sentido de un sello en la educación ciudadana como parte integral del proceso
formativo de la escuela, que excede un aprendizaje meramente cognitivo y que se
proyecta y actualiza en los espacios institucionales de deliberación y participación
política. Finalmente, el autor entrega valiosa evidencia descriptiva sobre el
comportamiento del liderazgo distribuido y del compromiso organizacional en las
escuelas chilenas.


::: {.callout-note title="How to cite this work"}

Eduardo Santander (2015). *¿Qué Puede Hacer La Cultura de La Escuela Para Aumentar La Participación Política de Sus Estudiantes? Un Estudio Exploratorio Sobre El Rol Del Liderazgo Distribuido y El Compromiso Organizacional Docente En Escuelas Chilenas*.  Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

