---
title : "Aspectos Subjetivos de La Meritocracia y Su Relación Con La Percepción de La Desigualdad En Chile"
date : "2015-01-01"
author : ["Alex Torres"]
publication : " Magister En Psicología Social Comunitaria - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Psicología Social Comunitaria - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "La desigualdad es señalada como uno de los principales riesgos para la estabilidad de las democracias. Chile es un caso peculiar, ya que a pesar de ser uno de los países con mayores niveles de desigualdad (índice GINI, por ejemplo) no presenta gran inestabilidad. En este contexto, se hace relevante estudiar los mecanismos a nivel psicológico que permitirían justificar la desigualdad de las sociedades, siendo la meritocracia una de las principales estrategias de las sociedades democráticas en la legitimación de las desigualdades sociales. El presente estudio de carácter cuantitativo no experimental, transversal y correlacional, propone medir la meritocracia diferenciando dos dimensiones: percepción y creencia meritocrática, e identificar en qué grado elementos de estatus individual (subjetivo, ingreso per cápita familiar y nivel educacional) se relacionan con cada dimensión, y la relación de ambas dimensiones con la percepción de la desigualdad salarial. Se utilizaron los datos del proyecto Fondecyt “Desigualdad, Justicia Social y Participación Ciudadana”, constituidos por 1.245 casos obtenidos mediante un muestreo probabilístico estratificado en 4 etapas (comunas, manzanas, vivienda, habitante). El modelo de medición de la meritocracia, así como la relación de ésta con los elementos individuales de estatus y desigualdad, fueron estimados mediante ecuaciones estructurales. Los resultados del estudio señalan que existe un funcionamiento diferenciado entre percepción y creencia en la meritocracia, que implica que estos debiesen distinguirse cada vez que se mida la meritocracia. Además, se observa que percepción y creencia meritocrática se asocian de forma distinta a los elementos individuales considerados en el modelo de este estudio: la percepción se encuentra influida por el estatus subjetivo y por el nivel educacional (de forma inversa), mientras que la creencia no se asocia a los elementos considerados en el modelo. Respecto de la desigualdad, se observa que la meritocracia funcionaria como una estrategia legitimadora, por un lado, al asociarse a la percepción de menores niveles de desigualdad (percepción) y, por otro, a desear mayores brechas salariales entre ocupaciones de alto y bajo estatus (creencia)."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: https://jc-castillo.com/docs/TesisAlexTorresMeritocracia.pdf
---
---

# Resumen
La desigualdad es señalada como uno de los principales riesgos para la
estabilidad de las democracias. Chile es un caso peculiar, ya que a pesar de ser uno de
los países con mayores niveles de desigualdad (índice GINI, por ejemplo) no presenta
gran inestabilidad. En este contexto, se hace relevante estudiar los mecanismos a nivel
psicológico que permitirían justificar la desigualdad de las sociedades, siendo la
meritocracia una de las principales estrategias de las sociedades democráticas en la
legitimación de las desigualdades sociales.
El presente estudio de carácter cuantitativo no experimental, transversal y
correlacional, propone medir la meritocracia diferenciando dos dimensiones: percepción
y creencia meritocrática, e identificar en qué grado elementos de estatus individual
(subjetivo, ingreso per cápita familiar y nivel educacional) se relacionan con cada
dimensión, y la relación de ambas dimensiones con la percepción de la desigualdad
salarial. Se utilizaron los datos del proyecto Fondecyt “Desigualdad, Justicia Social y
Participación Ciudadana”, constituidos por 1.245 casos obtenidos mediante un muestreo
probabilístico estratificado en 4 etapas (comunas, manzanas, vivienda, habitante). El
modelo de medición de la meritocracia, así como la relación de ésta con los elementos
individuales de estatus y desigualdad, fueron estimados mediante ecuaciones
estructurales.
Los resultados del estudio señalan que existe un funcionamiento diferenciado
entre percepción y creencia en la meritocracia, que implica que estos debiesen
distinguirse cada vez que se mida la meritocracia. Además, se observa que percepción y
creencia meritocrática se asocian de forma distinta a los elementos individuales
considerados en el modelo de este estudio: la percepción se encuentra influida por el
estatus subjetivo y por el nivel educacional (de forma inversa), mientras que la creencia
no se asocia a los elementos considerados en el modelo. Respecto de la desigualdad, se
observa que la meritocracia funcionaria como una estrategia legitimadora, por un lado,
al asociarse a la percepción de menores niveles de desigualdad (percepción) y, por otro,
a desear mayores brechas salariales entre ocupaciones de alto y bajo estatus (creencia).


::: {.callout-note title="How to cite this work"}

Alex Torres (2015). *Aspectos Subjetivos de La Meritocracia y Su Relación Con La Percepción de La Desigualdad En Chile*.  Magister En Psicología Social Comunitaria - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

