---
title : "Legitimidad Del Sistema Económico y Participación Ciudadana: Una Aproximación a La Relación Entre Percepciones Individuales y Actividad Política En Chile"
date : "2016-01-01"
author : ["Matias Placencio-Castro"]
publication : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "Este estudio investiga la relación entre las percepciones individuales sobre la legitimidad del sistema económico y la participación política en Chile. A través de un enfoque sociológico, se analiza cómo las opiniones sobre la distribución de recompensas en la sociedad influyen en las acciones políticas de los ciudadanos. Se emplea la teoría de la equidad y la justicia procedimental como marcos conceptuales para comprender este fenómeno. Los datos utilizados provienen del Estudio Nacional sobre el Conflicto y la Cohesión Social en Chile, realizado por el Centro de Estudios del Conflicto y la Cohesión Social (COES) en 2014. La muestra incluyó a 2,025 personas de 18 a 75 años residentes en 22 ciudades de Chile, con un error muestral del 2.2% bajo un supuesto de Muestreo Aleatorio Simple. El análisis se basa en datos empíricos recopilados mediante el Análisis de Clases Latentes, que permiten identificar perfiles de participación y explorar la diversificación del repertorio político en la ciudadanía chilena. Se destaca la importancia de considerar la educación y los ingresos como factores que pueden influir en las percepciones de deprivación relativa y, por ende, en la motivación para la acción política. Los resultados preliminares sugieren que las percepciones sobre la legitimidad del sistema económico juegan un papel significativo en el comportamiento político de los individuos, especialmente en un contexto de crisis de representatividad y distanciamiento entre la política partidista y la ciudadanía común. Se plantea la necesidad de profundizar en la comprensión de estos mecanismos para abordar los desafíos actuales en materia de participación política y legitimidad institucional en Chile."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: https://jc-castillo.com/docs/FinalCorregidaAgosto2016.pdf
---
---

# Resumen
Este estudio investiga la relación entre las percepciones individuales sobre la legitimidad del sistema económico y la participación política en Chile. A través de un enfoque sociológico, se analiza cómo las opiniones sobre la distribución de recompensas en la sociedad influyen en las acciones políticas de los ciudadanos. Se emplea la teoría de la equidad y la justicia procedimental como marcos conceptuales para comprender este fenómeno.

Los datos utilizados provienen del Estudio Nacional sobre el Conflicto y la Cohesión Social en Chile, realizado por el Centro de Estudios del Conflicto y la Cohesión Social (COES) en 2014. La muestra incluyó a 2,025 personas de 18 a 75 años residentes en 22 ciudades de Chile, con un error muestral del 2.2% bajo un supuesto de Muestreo Aleatorio Simple.

El análisis se basa en datos empíricos recopilados mediante el Análisis de Clases Latentes, que permiten identificar perfiles de participación y explorar la diversificación del repertorio político en la ciudadanía chilena. Se destaca la importancia de considerar la educación y los ingresos como factores que pueden influir en las percepciones de deprivación relativa y, por ende, en la motivación para la acción política.

Los resultados preliminares sugieren que las percepciones sobre la legitimidad del sistema económico juegan un papel significativo en el comportamiento político de los individuos, especialmente en un contexto de crisis de representatividad y distanciamiento entre la política partidista y la ciudadanía común. Se plantea la necesidad de profundizar en la comprensión de estos mecanismos para abordar los desafíos actuales en materia de participación política y legitimidad institucional en Chile.


::: {.callout-note title="How to cite this work"}

Matias Placencio-Castro (2016). *Legitimidad Del Sistema Económico y Participación Ciudadana: Una Aproximación a La Relación Entre Percepciones Individuales y Actividad Política En Chile*.  Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

