---
title : "Desigualdad y Compromiso Cı́vico de Los Jóvenes Chilenos: Una Mirada al Perı́odo (2009-2014)"
date : "2016-01-01"
author : ["Francisca Acevedo"]
publication : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "el objetivo final de esta investigación consiste en realizar un aporte a la visión que se tiene respecto al compromiso cı́vico juvenil chileno de una manera especı́fica, y desde una aproximación cuantitativa al problema, que sirva como complemento a los estudios previamente realizados sobre este tema, los cuales han sido mayoritariamente de carácter cualitativo (Martı́nez and Cumsille, 2010; Martı́nez et al., 2010, 2012). Esto, con el afán de comprender de mejor manera cómo es que el compromiso cı́vico se da en esta etapa, dándole énfasis a ciertos factores que generan desigualdad a nivel individual, y con ello, generar evidencia que ayude a la generación de instancias y programas que lo fomenten a futuro. Para efectuar los análisis correspondientes se utilizaron los datos provistos por la “Encuesta Jóvenes, Participación y Consumo de Medios” realizada por la Escuela de Perio- dismo de la Universidad Diego Portales en conjunto con Feedback (agencia profesional de encuestas), especı́ficamente sus versiones para el año 2010 y 2014, ambos años posteriores a las últimas elecciones presidenciales en Chile. Este instrumento se prefiere por sobre otros por las temáticas especı́ficas que aborda, y porque cuenta con indicadores claves para medir el compromiso cı́vico de la manera propuesta. Además, cuenta con datos más actualizados en comparación con otras encuestas dirigidas a la juventud chilena, lo que permite visualizar los cambios ocurridos en el último tiempo (a partir de los años 2011-2012)."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href:  /documents/pdf/acevedoversionfinal.pdf
---
---

# Resumen

el objetivo final de esta investigación consiste en realizar un
aporte a la visión que se tiene respecto al compromiso cı́vico juvenil chileno de una manera
especı́fica, y desde una aproximación cuantitativa al problema, que sirva como complemento
a los estudios previamente realizados sobre este tema, los cuales han sido mayoritariamente
de carácter cualitativo (Martı́nez and Cumsille, 2010; Martı́nez et al., 2010, 2012). Esto, con
el afán de comprender de mejor manera cómo es que el compromiso cı́vico se da en esta
etapa, dándole énfasis a ciertos factores que generan desigualdad a nivel individual, y con
ello, generar evidencia que ayude a la generación de instancias y programas que lo fomenten
a futuro.
Para efectuar los análisis correspondientes se utilizaron los datos provistos por la
“Encuesta Jóvenes, Participación y Consumo de Medios” realizada por la Escuela de Perio-
dismo de la Universidad Diego Portales en conjunto con Feedback (agencia profesional de
encuestas), especı́ficamente sus versiones para el año 2010 y 2014, ambos años posteriores a
las últimas elecciones presidenciales en Chile. Este instrumento se prefiere por sobre otros
por las temáticas especı́ficas que aborda, y porque cuenta con indicadores claves para medir
el compromiso cı́vico de la manera propuesta. Además, cuenta con datos más actualizados
en comparación con otras encuestas dirigidas a la juventud chilena, lo que permite visualizar
los cambios ocurridos en el último tiempo (a partir de los años 2011-2012).


::: {.callout-note title="How to cite this work"}

Francisca Acevedo (2016). *Desigualdad y Compromiso Cı́vico de Los Jóvenes Chilenos: Una Mirada al Perı́odo (2009-2014)*.  Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

