---
title : "Merezco estar aquı́: Un estudio multinivel sobre la relación entre meritocracia y educación"
date : "2017-01-01"
author : ["Diego Sandoval"]
publication : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "A pesar de que la existencia efectiva de la meritocracia ha sido cuestionada empı́ricamente por la literatura especializada en desigualdad, percepciones y creencias respecto a esta explicación racional de las diferencias de status dentro de la sociedad son comúnmente favorables. La transmisión de esta narrativa, para Lampert (2014), se lleva a cabo en las escuelas: profundamente asentada en el discurso pedagógico y en mecanismos de evaluación, la meritocracia se tiende a concebir como un orden natural apoyado por el “empiricismo” de la distribución normal. Desde dicha problemática nace nuestra pregunta de investigación: en contexto comparado, ¿se asocia el nivel educativo con mayores percepciones y creencias en la meritocracia? Utilizando los datos de International Social Survey Programme del año 2009 (Social Inequality IV ), la metodologı́a de análisis consiste en la construcción de escalas de percepción y creencias meritocráticas a través de Análisis Factorial Confirmatorio, para luego dar paso a la estimación de modelos Multinivel. Los principales resultados apuntan a confirmar el diagnóstico de Lampert, pero solamente para paı́ses con altos niveles de desigualdad. En paı́ses con menor coeficiente de Gini, la gente más educada tenderá a ser más crı́tica del discurso meritocrático. Asimismo, se encuentra que la ex pertenencia al bloque soviético modera la relación entre edad y las variables dependientes."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: /tesis/2019_explorando_la_asocia/#documento
---
---

# Resumen

A pesar de que la existencia efectiva de la meritocracia ha sido cuestionada empı́ricamente por la
literatura especializada en desigualdad, percepciones y creencias respecto a esta explicación racional
de las diferencias de status dentro de la sociedad son comúnmente favorables. La transmisión de
esta narrativa, para Lampert (2014), se lleva a cabo en las escuelas: profundamente asentada en el
discurso pedagógico y en mecanismos de evaluación, la meritocracia se tiende a concebir como un
orden natural apoyado por el “empiricismo” de la distribución normal. Desde dicha problemática
nace nuestra pregunta de investigación: en contexto comparado, ¿se asocia el nivel educativo con
mayores percepciones y creencias en la meritocracia? Utilizando los datos de International Social
Survey Programme del año 2009 (Social Inequality IV ), la metodologı́a de análisis consiste en
la construcción de escalas de percepción y creencias meritocráticas a través de Análisis Factorial
Confirmatorio, para luego dar paso a la estimación de modelos Multinivel. Los principales resultados
apuntan a confirmar el diagnóstico de Lampert, pero solamente para paı́ses con altos niveles de
desigualdad. En paı́ses con menor coeficiente de Gini, la gente más educada tenderá a ser más
crı́tica del discurso meritocrático. Asimismo, se encuentra que la ex pertenencia al bloque soviético
modera la relación entre edad y las variables dependientes.

# Documento

<iframe src="https://www.dropbox.com/s/hd34jusmqum3lb1/Tesis%20Diego%20Sandoval.pdf?raw=1" style="min-height:100vh;width:100%" frameborder="0"></iframe>


::: {.callout-note title="How to cite this work"}

Diego Sandoval (2017). *Merezco estar aquı́: Un estudio multinivel sobre la relación entre meritocracia y educación*.  Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

