---
title : "Justicia de las pensiones en Chile: una evaluación desde las características individuales y las preferencias distributivas de la población en la Región Metropolitana"
date : "2017-12-01"
author : ["Esteban Munoz"]
publication : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "Esta tesis busca aportar al debate sobre las pensiones de vejez en Chile desde la justicia social empírica. La pregunta principal que se busca responder es ¿qué características sociodemográficas y cuáles preferencias distributivas son tomadas en cuenta al evaluar la justicia (o injusticia) de una pensión en Chile? Otras preguntas que motivan este trabajo son: ¿cómo es la distribución actual de las pensiones? ¿qué se considera una pensión justa hoy en Chile? Y ¿cómo varían estas distribuciones en la población? Para evaluar la justicia de las pensiones en Chile se utiliza la conocida función de evaluación de justicia de Jasso (1978), que permite cuantificar escenarios de justicia e injusticia sobre determinados bienes. Los datos corresponden a la primera y segunda ola de la encuesta “Estudio Desigualdad, Justicia Social y Participación Política” (2014), perteneciente al proyecto FONDECYT 11121203. La muestra final es de 416 observaciones. Se estiman modelos de selección de Heckman para evaluar la justicia de las pensiones. Los resultados indican que las evaluaciones sobre la justicia de las pensiones dependen tanto de factores sociodemográficos, como también de preferencias distributivas. Además, estos resultados vienen a confirmar los hallazgos de investigaciones recientes sobre las pensiones en Chile, tanto por el pesimismo respecto de éstas, como por las expectativas sobre lo que se considera una pensión razonable o, en este caso, una pensión justa."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: /tesis/2019_explorando_la_asocia/#documento
---
---

# Resumen

Esta tesis busca aportar al debate sobre las pensiones de vejez en Chile
desde la justicia social empírica. La pregunta principal que se busca responder es
¿qué características sociodemográficas y cuáles preferencias distributivas son
tomadas en cuenta al evaluar la justicia (o injusticia) de una pensión en Chile? Otras
preguntas que motivan este trabajo son: ¿cómo es la distribución actual de las
pensiones? ¿qué se considera una pensión justa hoy en Chile? Y ¿cómo varían
estas distribuciones en la población? Para evaluar la justicia de las pensiones en
Chile se utiliza la conocida función de evaluación de justicia de Jasso (1978), que
permite cuantificar escenarios de justicia e injusticia sobre determinados bienes. Los
datos corresponden a la primera y segunda ola de la encuesta “Estudio
Desigualdad, Justicia Social y Participación Política” (2014), perteneciente al
proyecto FONDECYT 11121203. La muestra final es de 416 observaciones. Se
estiman modelos de selección de Heckman para evaluar la justicia de las pensiones.
Los resultados indican que las evaluaciones sobre la justicia de las pensiones
dependen tanto de factores sociodemográficos, como también de preferencias
distributivas. Además, estos resultados vienen a confirmar los hallazgos de
investigaciones recientes sobre las pensiones en Chile, tanto por el pesimismo
respecto de éstas, como por las expectativas sobre lo que se considera una pensión
razonable o, en este caso, una pensión justa.

<iframe src="https://www.dropbox.com/s/xv5ou2r0jyebzou/Tesis%20-%20Esteban%20Munoz_entrega%20final.pdf?raw=1" style="min-height:100vh;width:100%" frameborder="0"></iframe>


::: {.callout-note title="How to cite this work"}

Esteban Munoz (2017). *Justicia de las pensiones en Chile: una evaluación desde las características individuales y las preferencias distributivas de la población en la Región Metropolitana*.  Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

