---
title : "La Dimensión Subjetiva de La Desigualdad de Género En Ingresos: Factores Individuales Asociados a Evaluación de Lo Percibido y Lo Justo"
date : "2018-01-01"
author : ["Sebastian Rojas"]
publication : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "El presente trabajo de tesis tiene como objetivo analizar los factores individuales y contextuales que se asocian a la evaluación de justicia, con la particularidad de analizar ocupaciones y género. Este concepto refiere a la evaluación que hacen las personas en relación al salario percibido y justo para otras ocupaciones ..."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: https://www.dropbox.com/s/trz1vbcbpmbgocj/210119_Tesis_Final_Defensa.pdf
---
---

# Resumen

El presente trabajo de tesis tiene como objetivo analizar los factores individuales
y contextuales que se asocian a la evaluación de justicia, con la particularidad de analizar
ocupaciones y género. Este concepto refiere a la evaluación que hacen las personas en
relación al salario percibido y justo para otras ocupaciones. Usando los datos de la en-
cuesta Desiguales del Programa de las Naciones Unidas Para del Desarrollo (N=2613),
estimamos regresiones lineales múltiples para probar una serie de factores que la literatura
indica como relevantes en la evaluación de justicia. Los resultados dan cuenta de que los
encuestados no difieren en sus evaluaciones de justicia según género, que la ocupación no
genera diferencias en la evaluación de los encuestados y que la educación, clase subjetiva
e ideologı́a polı́tica se comportan de manera distinta según el estatus de la ocupación, pero
no ası́ su género.
Se agradece al Centro de Estudios para el Conflicto y la Cohesión Social (COES)
(CONICYT/FONDAP/15130009) por el financiamiento de estudios de postgrado durante
el periodo de tesis.

# Documento

<iframe src="https://www.dropbox.com/s/trz1vbcbpmbgocj/210119_Tesis_Final_Defensa.pdf?raw=1" style="min-height:100vh;width:100%" frameborder="0"></iframe>


::: {.callout-note title="How to cite this work"}

Sebastian Rojas (2018). *La Dimensión Subjetiva de La Desigualdad de Género En Ingresos: Factores Individuales Asociados a Evaluación de Lo Percibido y Lo Justo*.  Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

