---
title : "Estatus social subjetivo y Percepción de meritocracia: El caso de Chile"
date : "2018-01-01"
author : ["Julio Iturra"]
publication : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "La meritocracia constituye uno de los ideales más representativos de las sociedades mo- dernas de occidente. El mérito, entendido como la combinación de esfuerzos y talentos individuales, constituye el fundamento de una sociedad basada en los principios merito- cráticos. La legitimidad de desigualdad social ..."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: /tesis/2018_estatus_social_subje/#documento
---
---

# Resumen

La meritocracia constituye uno de los ideales más representativos de las sociedades mo-
dernas de occidente. El mérito, entendido como la combinación de esfuerzos y talentos
individuales, constituye el fundamento de una sociedad basada en los principios merito-
cráticos. La legitimidad de desigualdad social posee un fuerte arraigo en la meritocracia,
de modo tal que individuos que se sitúan en estratos más altos de la jerarquía social se
conciben a sí mismos como merecedores de su posición. En este sentido ¿son las personas
con mayores ingresos, más educadas y con ocupaciones de mayor cualificación, las que
perciben más meritocracia? Así también ¿la percepción de sí mismos en la jerarquía so-
cial afecta cómo los individuos perciben el funcionamiento de la meritocracia? Esta tesis
analizó la relación de características objetivas y subjetivas de estatus social con la percep-
ción de meritocracia en Chile, con el objetivo de determinar en qué medida la experiencia
objetiva y las percepciones en torno al estatus social propio, de la familia de origen y de
los hijos en el futuro, se relacionan con la percepción de meritocracia. Utilizando datos
del Estudio Longitudinal Social de Chile (n=2983), se realizó un Análisis Factorial Con-
firmatorio que evidenció dos dimensiones a través de las cuales puede ser medida la
percepción de meritocracia. La primera dimensión guarda relación con la importancia de
la ambición, el educarse y el trabajo duro para surgir en la vida. La segunda dimensión
se relaciona el grado de acuerdo respecto a si en Chile a las personas son recompensadas
por sus esfuerzos y talento. Los resultados de los modelos de ecuaciones estructurales
evidenciaron que individuos más educados atribuyen más importancia a los factores in-
dividuales para salir adelante, pero a su vez sostienen una visión crítica respecto de las
recompensas provenientes del esfuerzo y el talento, mientras que los ingresos y la ocu-
pación no parecen ser relevantes. Respecto de la percepción de estatus social, el estatus
propio pierde relevancia al controlar por las medidas de estatus objetivas y subjetivas de
estatus, siendo el estatus de los hijos el más relevante, donde individuos con mayores ex-
pectativas de logro de estatus para sus hijos, son quienes atribuyen más importancia al
mérito individual, y al mismo tiempo, poseen una percepción crítica de las recompensas.
Se concluye que las apreciaciones sobre el estatus social en relación al pasado y al futuro,
como también el logro educacional, son altamente relevantes en explicar las percepciones
sobre la meritocracia en Chile.

# Documento

<iframe src="https://www.dropbox.com/s/edr1ji8mpo25qlu/Tesis_Iturra-Julio.pdf?raw=1" style="min-height:100vh;width:100%" frameborder="0"></iframe>


::: {.callout-note title="How to cite this work"}

Julio Iturra (2018). *Estatus social subjetivo y Percepción de meritocracia: El caso de Chile*.  Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

