---
title : "Balance Legistlativo, Adhesión al Sistema Político y Preferencias Redistributivas En América Latina"
date : "2018-01-01"
author : ["Sofia Montedonico"]
publication : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
publication_short : " Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile"
abstract : "Tradicionalmente las tendencias y partidos de izquierda se han asociado a un rol más activo del Estado en temas de redistribución. Este trabajo pretende ahondar en este punto, analizando en qué medida la composición de los parlamentos en términos de izquierda-derecha (balance legislativo) se relaciona con mayores o menores preferen- cias por redistribución por parte de la población. Los resultados del estudio demues- tran, primero, que a mayor tendencia hacia la izquierda en los aparatos legislativos, las preferencias redistributivas tienden a ser menores. En segundo lugar, la mayor adhe- sión al sistema polı́tico se asocia a un mayor grado de acuerdo con la reasignación de recursos, y por último, en paı́ses con alto número de polı́ticos de izquierda en el con- greso el efecto de la adhesión al sistema polı́tico es más grande y positivo respecto a la redistribución. Estos resultados se basan en un análisis Multinivel de Encuestas Repe- tidas con los datos de la encuesta LAPOP 2012 y 2014 para 18 paı́ses de América Latina, y muestran que la relación de las preferencias redistributivas con las caracterı́sticas del contexto polı́tico institucional son más complejas de lo que han demostrado estudios anteriores. Por todo lo anterior, se sugiere que para promover el apoyo a polı́ticas re- distributivas se debe desarrollar instituciones polı́ticas socialmente válidas y analizar los factores que están asociados a tendencia hacia la izquierda del aparato legislativo, dado que algún elemento de ello genera un desincentivo hacia la redistribución."
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: /documents/pdf/Tesis_SMontedónicoG.pdf
---
---

# Resumen

Tradicionalmente las tendencias y partidos de izquierda se han asociado a un rol más
activo del Estado en temas de redistribución. Este trabajo pretende ahondar en este
punto, analizando en qué medida la composición de los parlamentos en términos de
izquierda-derecha (balance legislativo) se relaciona con mayores o menores preferen-
cias por redistribución por parte de la población. Los resultados del estudio demues-
tran, primero, que a mayor tendencia hacia la izquierda en los aparatos legislativos, las
preferencias redistributivas tienden a ser menores. En segundo lugar, la mayor adhe-
sión al sistema polı́tico se asocia a un mayor grado de acuerdo con la reasignación de
recursos, y por último, en paı́ses con alto número de polı́ticos de izquierda en el con-
greso el efecto de la adhesión al sistema polı́tico es más grande y positivo respecto a la
redistribución. Estos resultados se basan en un análisis Multinivel de Encuestas Repe-
tidas con los datos de la encuesta LAPOP 2012 y 2014 para 18 paı́ses de América Latina,
y muestran que la relación de las preferencias redistributivas con las caracterı́sticas del
contexto polı́tico institucional son más complejas de lo que han demostrado estudios
anteriores. Por todo lo anterior, se sugiere que para promover el apoyo a polı́ticas re-
distributivas se debe desarrollar instituciones polı́ticas socialmente válidas y analizar
los factores que están asociados a tendencia hacia la izquierda del aparato legislativo,
dado que algún elemento de ello genera un desincentivo hacia la redistribución.


::: {.callout-note title="How to cite this work"}

Sofia Montedonico (2018). *Balance Legistlativo, Adhesión al Sistema Político y Preferencias Redistributivas En América Latina*.  Magister En Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile

:::

