---
title : "Determinantes de la percepción de seguridad frente al delito en la Región Metropolitana"
date : "2022-01-01"
author : ["Javiera Urrutia"]
publication : " Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
publication_short : " Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
abstract : "(Abstract not available)"
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: graduation-cap
      href: /tag/guia-o-cotutor/
---
---

# Resumen

En Chile, el organismo estatal encargado de medir fenómenos asociados a la delincuencia,
la victimización, la tasa de delitos y de (in)seguridad ciudadana, es el Instituto Nacional
de Estadísticas (INE), a través de la Encuesta Nacional Urbana de Seguridad Ciudadana
(ENUSC). Sin embargo, a pesar de contar con la disponibilidad de los datos, no hay
suficientes estudios que ahonden en un tema que ha cobrado especial relevancia, y que ha
ido en aumento en los últimos años en Chile: la percepción de inseguridad por parte de la
ciudadanía. El aumento de la percepción de inseguridad frente al delito en Chile es un
fenómeno sumamente llamativo, en tanto no se condice con las estadísticas objetivas, es
decir, que la delincuencia en Chile ha ido en descenso, y que, a nivel Latinoamericano,
Chile se posiciona como uno de los países más seguros de la región, según el índice de
paz global (2020). En este sentido, el objetivo de la presente investigación, es dilucidar
cuáles son los factores que influyen, en mayor medida, en que esta percepción de
inseguridad subjetiva vaya en aumento, aun cuando el índice de delitos (dimensión
objetiva), vaya en descenso, esto en la Región Metropolitana. Para esta finalidad, el
presente trabajo tendrá un enfoque cuantitativo, y los datos serán extraídos de la ENUSC
más reciente publicada, correspondiente al año 2019. La variable dependiente a medir
será la percepción de inseguridad frente al delito y las variables independientes se
concentrarán en los determinantes de esta percepción asociados cada uno a las cinco
teorías de inseguridad frente al delito –incivilidad, victimización, vulnerabilidad física,
social y redes sociales-. Los resultados de la investigación reportan que las cinco teorías
de inseguridad frente al delito son importantes para explicar el fenómeno de la percepción
de inseguridad, de igual forma, se evalúan de forma específica respecto a las variables
que contiene cada teoría. Se sugiere realizar una investigación que aborde el tema a nivel
país, o que se centre específicamente en los tipos de delito frente a los que la gente se
siente más vulnerable. Se finaliza con las limitaciones del estudio, y con consideraciones
finales que puedan aportar a la discusión de la seguridad ciudadana en Chile, y a re pensar
una ciudad en donde sus habitantes se sientan seguros de vivir.


::: {.callout-note title="How to cite this work"}

Javiera Urrutia (2022). *Determinantes de la percepción de seguridad frente al delito en la Región Metropolitana*.  Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile

:::

