---
title : "Bienestar, trabajo doméstico y uso del tiempo: un análisis cuantitativo del bienestar de las mujeres en Chile"
date : "2022-01-01"
author : ["Karen Tapia"]
publication : " Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
publication_short : " Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
abstract : "(Abstract not available)"
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: h
---
---

# Resumen
El bienestar se puede ver influido por una serie de elementos, como la edad, el nivel socioeconómico, el sexo, entre otros. Durante los últimos 40 años, la relevancia de la carga de trabajo doméstico ha logrado posicionarse como un elemento clave a la hora de analizar el bienestar, particularmente femenino.

La pregunta que guía esta investigación es: ¿en qué medida repercute la carga horaria de trabajo doméstico en el bienestar de las mujeres en Chile?. Este estudio tiene por objetivo evaluar el bienestar subjetivo de las mujeres a través de su componente cognitivo (satisfacción con la vida) y analizar su relación con la carga horaria de trabajo doméstico al interior de los hogares. Para ello, se utilizaron los datos de la Encuesta Nacional del Uso del Tiempo (2015), con una muestra final de 5623 casos. La población objetivo de esta investigación corresponde a hombres y mujeres que hayan contestado el Cuestionario de Uso del Tiempo (ENUT) 2015, mayores de 16 años, residentes en la Región Metropolitana. El análisis de los datos se llevó a cabo mediante dos procedimientos: primero un análisis bivariado de las principales variables de interés, y la elaboración de modelos de regresión lineales para observar la asociatividad entre variables.

Los resultados indican que la satisfacción con la vida se ve influenciada mayoritariamente por los ingresos, donde las mujeres de mayores ingresos dedican menos cantidad de horas al trabajo doméstico y gozan de mayor bienestar. A su vez, un hallazgo relevante para la medición de la satisfacción con la vida es que la satisfacción con el uso del tiempo determina en gran medida el bienestar.

Palabras clave: Bienestar, satisfacción con la vida, carga doméstica, trabajo doméstico, tiempo.


::: {.callout-note title="How to cite this work"}

Karen Tapia (2022). *Bienestar, trabajo doméstico y uso del tiempo: un análisis cuantitativo del bienestar de las mujeres en Chile*.  Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile

:::

