---
title : "Factores Determinantes de Las Trayectorias de Deserción Permanente En Educación Superior: El Efecto de Las Ayudas Financieras Estatales y La Política de Gratuidad"
date : "2022-01-01"
author : ["Catalina Miranda"]
publication : " Licenciatura En Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
publication_short : " Licenciatura En Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
abstract : "(Abstract not available)"
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: https://andreas-lafferte.github.io/tesis/resumen.html
---
---

# Resumen
El sistema de educación superior chileno ha experimentado profundas transformaciones
durante las últimas décadas. Una de ellas ha sido la considerable expansión en términos de
cobertura, en gran parte posibilitada por la ampliación y diversificación de las ayudas
financieras -becas y créditos- provistas por parte del Estado. Sin embargo, los avances en
materia de acceso no vinieron acompañados de la generación de condiciones que favorezcan
la retención y la permanencia, persistiendo aún elevadas tasas de deserción en el sistema. En
este escenario, la presente investigación se centró en las trayectorias académicas de los
estudiantes pertenecientes a la cohorte de ingreso del año 2016, con el fin de indagar en la
influencia que las ayudas financieras estatales anteriormente mencionadas -en particular la
reciente política de gratuidad- tienen sobre la probabilidad de abandonar permanentemente
los estudios superiores. Como hipótesis principales, se planteó que: i) contar con ayudas
financieras se asociaría con una menor probabilidad de desertar; y ii) los estudiantes
beneficiados con el Crédito con Garantía Estatal (CAE) presentarían una menor probabilidad
de desertar en comparación con aquellos beneficiarios de la gratuidad, así como también con
quienes cuentan con el Fondo Solidario de Crédito Universitario (FSCU). A partir de datos
provenientes de diversas fuentes estadísticas de educación superior de organismos estatales
entre los años 2016 y 2020, se clasificó a los estudiantes en función de sus trayectorias
académicas y se construyeron tablas de contingencia y modelos de regresiones logísticas para
evaluar el efecto que las diferentes ayudas económicas tienen sobre la probabilidad de
ocurrencia del fenómeno. Los resultados indican que los beneficiarios de ayudas financieras
efectivamente contaron con una menor probabilidad de abandonar los estudios, y pese a que
quienes contaron con CAE también presentaron una menor probabilidad de deserción en
comparación con quienes accedieron a gratuidad, esta diferencia no fue demasiado
significativa. Se identificó, también, que la probabilidad de deserción disminuyó entre
quienes combinaron becas y créditos en contraposición a quienes solo contaron con una beca,
demostrando que un aumento en el compromiso económico incide en una menor
probabilidad de abandono.


::: {.callout-note title="How to cite this work"}

Catalina Miranda (2022). *Factores Determinantes de Las Trayectorias de Deserción Permanente En Educación Superior: El Efecto de Las Ayudas Financieras Estatales y La Política de Gratuidad*.  Licenciatura En Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile

:::

