---
title : "¿Qué Pueden Hacer Las Escuelas Para Promover Actitudes Positivas Hacia La Igualdad de Derechos?"
date : "2023-03-01"
author : ["Anais Herrera"]
publication : " Magister En Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
publication_short : " Magister En Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile"
abstract : "(Abstract not available)"
abstract_short : ""
categories : ["Guía o cotutor"]
about:
  template: marquee
  links:
    - icon: file-pdf-fill
      href: https://anaisherrera.github.io/tesis/
    - icon: github
      href: https://github.com/anaisherrera/tesis/
---
En un mundo con altos niveles de desigualdad y crecientes expresiones de intoleran-
cia, se hace fundamental la aprobación de políticas públicas que avancen a garantizar
la igualdad de derechos. En sociedades democráticas la promoción de estas políticas
depende en parte importante de la opinión de la ciudadanía. Uno de los principales
espacios en los que el Estado puede intervenir para promover actitudes positivas hacia
la igualdad de derechos es la escuela, por su rol fundamental en la socialización de
principios y valores. Diversas investigaciones han indagado en los factores asociados a
las actitudes hacia la igualdad de derechos de los jóvenes en edad escolar, orientándose
en dos líneas: una relacionada con características y experiencias individuales de los
estudiantes, y otra enfocada en características y prácticas de la escuela a la que asis-
ten. La presente investigación pretende aportar a estas líneas de estudio incorporando
ambas teorías en un modelo estadístico para evaluar si alguna de las características
de la escuela (señaladas frecuentemente en investigaciones anteriores) posee la ca-
pacidad de disminuir las diferencias individuales en las actitudes hacia la igualdad
de derechos. Para ello se estiman regresiones multinivel utilizando datos del Estudio Internacional sobre Educación Cívica y Ciudadana (ICCS) 2016 de 3.920 estudiantes
de 8°básico de 166 escuelas chilenas. Los resultados indican que las buenas relaciones
entre estudiantes y profesores son capaces de disminuir el efecto del sexo y el nivel de
conocimiento cívico en dos de las tres dimensiones de las actitudes hacia la igualdad
de derechas analizadas en el estudio.


::: {.callout-note title="How to cite this work"}

Anais Herrera (2023). *¿Qué Pueden Hacer Las Escuelas Para Promover Actitudes Positivas Hacia La Igualdad de Derechos?*.  Magister En Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile

:::

